## Importação das Bibliotecas

In [1]:
import pandas as pd
import numpy as np

## Extração da Base Completa

In [2]:
dataframe = pd.read_csv(r'C:\7DaysOfCode\Emprestimos_Bibliotecas.csv')

## Remoção de Colunas Irrelevantes

In [3]:
dataframe = dataframe.drop(columns={"Unnamed: 0", "registro_sistema"}, axis=0)

## Verificação e Alteração dos Tipos das Colunas

In [4]:
dataframe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2072522 entries, 0 to 2072521
Data columns (total 12 columns):
 #   Column                Dtype
---  ------                -----
 0   id_emprestimo         int64
 1   codigo_barras         object
 2   data_renovacao        object
 3   data_emprestimo       object
 4   data_devolucao        object
 5   matricula_ou_siape    float64
 6   tipo_vinculo_usuario  object
 7   id_exemplar           int64
 8   colecao               object
 9   biblioteca            object
 10  status_material       object
 11  localizacao           int64
dtypes: float64(1), int64(3), object(8)
memory usage: 189.7+ MB

In [5]:
dataframe['matricula_ou_siape'] = dataframe['matricula_ou_siape'].astype(object)
dataframe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2072522 entries, 0 to 2072521
Data columns (total 12 columns):
 #   Column                Dtype
---  ------                -----
 0   id_emprestimo         int64
 1   codigo_barras         object
 2   data_renovacao        object
 3   data_emprestimo       object
 4   data_devolucao        object
 5   matricula_ou_siape    object
 6   tipo_vinculo_usuario  object
 7   id_exemplar           int64
 8   colecao               object
 9   biblioteca            object
 10  status_material       object
 11  localizacao           int64
dtypes: int64(3), object(9)
memory usage: 189.7+ MB

## Criação da Coluna de Classificação das Áreas Referente ao CDU

In [6]:
condicoes = [
    dataframe['localizacao'] <= 99,
    dataframe['localizacao'] <= 199,
    dataframe['localizacao'] <= 299,
    dataframe['localizacao'] <= 399,
    dataframe['localizacao'] <= 499,
    dataframe['localizacao'] <= 599,
    dataframe['localizacao'] <= 699,
    dataframe['localizacao'] <= 799,
    dataframe['localizacao'] <= 899,
    dataframe['localizacao'] <= 999
]

areas = [
    'Generalidades. Ciência e conhecimento.',
    'Filosofia e psicologia.',
    'Religião.',
    'Ciências sociais.',
    'Classe vaga. Provisoriamente não ocupada.',
    'Matemática e ciências naturais.',
    'Ciências aplicadas.',
    'Belas artes.',
    'Linguagem. Língua. Linguística.',
    'Geografia. Biografia. História.'
]

In [7]:
dataframe['area'] = np.select(condicoes, areas)
dataframe

,id_emprestimo,codigo_barras,data_renovacao,data_emprestimo,data_devolucao,matricula_ou_siape,tipo_vinculo_usuario,id_exemplar,colecao,biblioteca,status_material,localizacao,area
0,709684,L095049,NaN,2010/01/04 07:44:10.721000000,2010/01/05 16:26:12.662000000,2008023265.0,ALUNO DE GRADUAÇÃO,13259,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,630,Ciências aplicadas.
1,709685,L167050,NaN,2010/01/04 07:44:10.750000000,2010/01/12 07:34:13.934000000,2008023265.0,ALUNO DE GRADUAÇÃO,70865,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,647,Ciências aplicadas.
2,709686,2006017618,2010/01/26 08:07:01.738000000,2010/01/04 08:08:44.081000000,2010/02/25 07:36:25.800000000,2008112114.0,ALUNO DE PÓS-GRADUAÇÃO,195347,Acervo Circulante,Biblioteca Setorial Prof. Rodolfo Helinski - E...,REGULAR,640,Ciências aplicadas.
3,709687,L184117,2010/01/18 11:07:46.470000000,2010/01/04 08:24:21.284000000,2010/02/03 08:58:45.692000000,200721119.0,ALUNO DE GRADUAÇÃO,131639,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,609,Ciências aplicadas.
4,709688,2007027500,2010/01/19 15:59:26.464000000,2010/01/04 08:27:33.569000000,2010/02/03 13:06:30.662000000,2009045971.0,ALUNO DE GRADUAÇÃO,225646,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,686,Ciências aplicadas.
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2072517,2989086,2008047044,NaN,2020/05/05 19:51:06.059000000,2021/05/13 14:53:31.000000000,3067431.0,SERVIDOR TÉCNICO-ADMINISTRATIVO,256297,Acervo Circulante,Biblioteca Setorial da Faculdade de Ciências d...,REGULAR,684,Ciências aplicadas.
2072518,2989087,2008047047,NaN,2020/05/05 19:51:06.135000000,2021/05/13 14:53:38.000000000,3067431.0,SERVIDOR TÉCNICO-ADMINISTRATIVO,256406,Acervo Circulante,Biblioteca Setorial da Faculdade de Ciências d...,REGULAR,628,Ciências aplicadas.
2072519,2989088,2010052905,NaN,2020/05/05 19:51:06.164000000,2021/05/13 15:01:46.000000000,3067431.0,SERVIDOR TÉCNICO-ADMINISTRATIVO,807821,Acervo Circulante,Biblioteca Setorial da Faculdade de Ciências d...,REGULAR,653,Ciências aplicadas.
2072520,2989089,2010048023,NaN,2020/06/09 11:54:02.669000000,2021/07/21 15:33:55.000000000,20201014993.0,ALUNO DE PÓS-GRADUAÇÃO,804885,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,675,Ciências aplicadas.
2072521,2989090,2013106838,NaN,2020/06/09 11:54:02.852000000,2021/07/21 15:33:45.000000000,20201014993.0,ALUNO DE PÓS-GRADUAÇÃO,1099777,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,14,Generalidades. Ciência e conhecimento.